### ISSUE TITLE
Dependency on JOCL ?

### ISSUE THREAD

**Issue by cdlm** [thi-ng/raymarchcl#2]
The `rm/test-render` call from the readme file complains about JOCL not being available:

```
JogampRuntimeException JOCL is not available  com.jogamp.opencl.CLPlatform.initialize (CLPlatform.java:180)
```

I tried adding the dependency to `project.clj` but that doesn't seem to have any effect… I don't have much experience with clojure so I'm stumped there. I'm trying this on OS X 10.9 and a MacBook Pro that should have OpenCL available.

**Comment by postspectacular** [comment]
Hmmm.... Which version of leiningen are you using? Might have something to do with classpath and (i think) that error is about JOCL's missing native dependencies rather than lack of actual OCL support (am still on 10.8.5 and it works).

**Comment by cdlm** [comment]
`Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(™) 64-Bit Server VM`

I did install some JDKs besides the one that comes with OS X, which might be the problem. But otherwise, JOCL doesn't seem to have much in the way of installation instructions, besides the maven excerpt…

**Comment by postspectacular** [comment]
That's the same lein version as I'm using and I too don't use the outdated Apple JDK (but Oracle JDK1.8.0_25)... There're a few things to try and I would highly appreciate any help in tracking this down since some canonical info about handling upstream native deps in leiningen still seems to be lacking (also see https://github.com/technomancy/leiningen/issues/1385)

### Experiment 1

```
cd raymarchcl
lein repl
```

...and then in the REPL:

``` clojure
(import 'com.jogamp.opencl.CLPlatform)
(CLPlatform/listCLPlatforms)
```

On my MBP (2010) I get this:

```
#object["[Lcom.jogamp.opencl.CLPlatform;" 0x3c79e6cc "[Lcom.jogamp.opencl.CLPlatform;@3c79e6cc"]
```

If you do get a (platform) result back from that call, then also try the following (still from the REPL):

``` clojure
(require '[thi.ng.simplecl.core :as cl])
(cl/available-devices (cl/select-platform))
```

should show something along the lines of:

```
[#object[com.jogamp.opencl.CLDevice 0x78aa798 "CLDevice [id: 4294967295 name: Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz type: CPU profile: FULL_PROFILE]"] #object[com.jogamp.opencl.CLDevice 0x2abeb654 "CLDevice [id: 16918016 name: GeForce GT 330M type: GPU profile: FULL_PROFILE]"]]
```

If you're getting a JOCL error again, can you then immediately call `(.printStackTrace *e)` and copy the trace here?

### Experiment 2

If you can be bothered could you also try cloning the SimpleCL repo and run one of the examples? E.g. https://github.com/thi-ng/simplecl/#hello-cl-example Any luck?

### Experiment 3

Edit `project.clj` in your clone of this project repo and add the following dependencies to the `:dependencies` vector:

``` clojure
[org.jogamp.gluegen/gluegen-rt-main "2.3.1"]
[org.jogamp.gluegen/gluegen-rt "2.3.1" :native-prefix ""]
[org.jogamp.jocl/jocl-main "2.3.1"]
[org.jogamp.jocl/jocl "2.3.1" :native-prefix ""]
```

Save and then launch the REPL again and try 1st experiment once more...

### Experiment 4

Go to the [JOCL website](http://jogamp.org/jocl-demos/www/) and try running the OpenCL info example (it's a Java WebStart app) - any joy with that?

**Comment by cdlm** [comment]
### Experiment 1

```
user=> (import 'com.jogamp.opencl.CLPlatform)
com.jogamp.opencl.CLPlatform
user=> (CLPlatform/listCLPlatforms)

JogampRuntimeException JOCL is not available  com.jogamp.opencl.CLPlatform.initialize (CLPlatform.java:180)
user=> (.printStackTrace *e)
com.jogamp.common.JogampRuntimeException: JOCL is not available
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:180)
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:156)
    at com.jogamp.opencl.CLPlatform.listCLPlatforms(CLPlatform.java:229)
    at com.jogamp.opencl.CLPlatform.listCLPlatforms(CLPlatform.java:220)
    at user$eval1468.invoke(form-init6546456210128351246.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6792)
    at clojure.lang.Compiler.eval(Compiler.java:6755)
    at clojure.core$eval.invoke(core.clj:3079)
    at clojure.main$repl$read_eval_print__7095$fn__7098.invoke(main.clj:240)
    at clojure.main$repl$read_eval_print__7095.invoke(main.clj:240)
    at clojure.main$repl$fn__7104.invoke(main.clj:258)
    at clojure.main$repl.doInvoke(main.clj:258)
    at clojure.lang.RestFn.invoke(RestFn.java:1523)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__881.invoke(interruptible_eval.clj:53)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:628)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1866)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:51)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__923$fn__926.invoke(interruptible_eval.clj:183)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__916.invoke(interruptible_eval.clj:152)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
nil
user=>
```

### Experiment 2

No luck:

```
$ lein trampoline run -m thi.ng.simplecl.test.hello
Retrieving criterium/criterium/0.4.3/criterium-0.4.3.pom from clojars
Retrieving criterium/criterium/0.4.3/criterium-0.4.3.jar from clojars
Reflection warning, /private/var/folders/c_/x0gn4hs5155_xncb_c2ptvch0000gn/T/form-init6691627369237494658.clj:1:974 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
Reflection warning, thi/ng/simplecl/core.clj:138:16 - call to method listCLDevices on com.jogamp.opencl.CLPlatform can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:148:22 - reference to field getMaxFlopsDevice can't be resolved.
Reflection warning, thi/ng/simplecl/core.clj:152:7 - call to method getMaxFlopsDevice can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:155:7 - call to method getMaxFlopsDevice can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:182:8 - call to method position can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:183:8 - call to method limit can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:184:17 - reference to field slice can't be resolved.
Reflection warning, thi/ng/simplecl/core.clj:185:10 - call to method position can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:186:20 - reference to field capacity can't be resolved.
Reflection warning, thi/ng/simplecl/core.clj:186:10 - call to method limit can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:207:12 - reference to field get on java.nio.Buffer can't be resolved.
Reflection warning, thi/ng/simplecl/core.clj:298:9 - call to static method create on com.jogamp.opencl.CLContext can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:310:12 - call to method build on com.jogamp.opencl.CLProgram can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:341:1 - call to method createByteBuffer on com.jogamp.opencl.CLContext can't be resolved (argument types: int, unknown).
Reflection warning, thi/ng/simplecl/core.clj:492:1 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:493:1 - call to method put on java.nio.DoubleBuffer can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:494:1 - call to method put on java.nio.FloatBuffer can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:495:1 - call to method put on java.nio.IntBuffer can't be resolved (argument types: unknown).
Reflection warning, thi/ng/simplecl/core.clj:528:1 - call to method put can't be resolved (target class is unknown).
Reflection warning, thi/ng/simplecl/core.clj:528:1 - call to method createBuffer on com.jogamp.opencl.CLContext can't be resolved (argument types: unknown, unknown).
Reflection warning, thi/ng/simplecl/core.clj:529:1 - call to method createBuffer on com.jogamp.opencl.CLContext can't be resolved (argument types: unknown, unknown).
Reflection warning, thi/ng/simplecl/core.clj:530:1 - call to method createBuffer on com.jogamp.opencl.CLContext can't be resolved (argument types: unknown, unknown).
Reflection warning, thi/ng/simplecl/core.clj:531:1 - call to method createBuffer on com.jogamp.opencl.CLContext can't be resolved (argument types: unknown, unknown).
Reflection warning, thi/ng/simplecl/ops.clj:207:21 - reference to field asIntBuffer on java.nio.Buffer can't be resolved.
Reflection warning, thi/ng/simplecl/ops.clj:208:23 - reference to field asFloatBuffer on java.nio.Buffer can't be resolved.
Reflection warning, thi/ng/simplecl/ops.clj:209:24 - reference to field asDoubleBuffer on java.nio.Buffer can't be resolved.
Reflection warning, thi/ng/simplecl/ops.clj:211:37 - reference to field capacity can't be resolved.
Exception in thread "main" com.jogamp.common.JogampRuntimeException: JOCL is not available, compiling:(/private/var/folders/c_/x0gn4hs5155_xncb_c2ptvch0000gn/T/form-init6691627369237494658.clj:1:125)
    at clojure.lang.Compiler.load(Compiler.java:7249)
    at clojure.lang.Compiler.loadFile(Compiler.java:7175)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: com.jogamp.common.JogampRuntimeException: JOCL is not available
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:180)
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:156)
    at com.jogamp.opencl.CLPlatform.getDefault(CLPlatform.java:189)
    at thi.ng.simplecl.core$select_platform.invoke(core.clj:116)
    at thi.ng.simplecl.core$init_state.doInvoke(core.clj:365)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at thi.ng.simplecl.test.hello$hello_cl.doInvoke(hello.clj:28)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at thi.ng.simplecl.test.hello$_main.doInvoke(hello.clj:51)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.Var.invoke(Var.java:375)
    at user$eval7.invoke(form-init6691627369237494658.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6792)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.load(Compiler.java:7237)
    ... 11 more
```

### Experiment 3

Pretty similar to first one:

```
$ g diff
diff --git i/project.clj w/project.clj
index bfb562b..bece1d8 100644
--- i/project.clj
+++ w/project.clj
@@ -11,5 +11,9 @@
                  [thi.ng/simplecl "0.2.2"]
                  [thi.ng/geom "0.0.803"]
                  [thi.ng/math "0.1.0"]
-                 [com.postspectacular/piksel "0.1.4"]]
+                 [com.postspectacular/piksel "0.1.4"]
+                 [org.jogamp.gluegen/gluegen-rt-main "2.3.1"]
+                 [org.jogamp.gluegen/gluegen-rt "2.3.1" :native-prefix ""]
+                 [org.jogamp.jocl/jocl-main "2.3.1"]
+                 [org.jogamp.jocl/jocl "2.3.1" :native-prefix ""]]
   :jvm-opts ["-server" "-Xms1g" "-Xmx2g"])
$ lein repl
nREPL server started on port 65106 on host 127.0.0.1 - nrepl://127.0.0.1:65106
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.7.0-RC1
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[thi.ng.simplecl.core :as cl])
nil
user=> (cl/available-devices (cl/select-platform))

JogampRuntimeException JOCL is not available  com.jogamp.opencl.CLPlatform.initialize (CLPlatform.java:180)
user=> (.printStackTrace *e)
com.jogamp.common.JogampRuntimeException: JOCL is not available
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:180)
    at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:156)
    at com.jogamp.opencl.CLPlatform.getDefault(CLPlatform.java:189)
    at thi.ng.simplecl.core$select_platform.invoke(core.clj:116)
    at user$eval1790.invoke(form-init251329441231869695.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6792)
    at clojure.lang.Compiler.eval(Compiler.java:6755)
    at clojure.core$eval.invoke(core.clj:3079)
    at clojure.main$repl$read_eval_print__7095$fn__7098.invoke(main.clj:240)
    at clojure.main$repl$read_eval_print__7095.invoke(main.clj:240)
    at clojure.main$repl$fn__7104.invoke(main.clj:258)
    at clojure.main$repl.doInvoke(main.clj:258)
    at clojure.lang.RestFn.invoke(RestFn.java:1523)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__881.invoke(interruptible_eval.clj:53)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:628)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1866)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:51)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__923$fn__926.invoke(interruptible_eval.clj:183)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__916.invoke(interruptible_eval.clj:152)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
nil
user=>
```

### Experiment 4

I'm getting a _this is a Java web start app, you need to download Java, here's a link to Oracle's web site_ popup… so how is `lein` running exactly?

**Comment by postspectacular** [comment]
JOCL is separate to lein/clojure - it's a Java API and partially autogenerated from C header files (via gluegen). TBH I've been using this on quite a few projects on a variety of machines (OSX, Win7/8, Ubuntu) and not once had issues like this... I still believe though the only real issue here is that JOCL doesn't find it's native libraries when you first try to instantiate it and I currently have no idea why this would be the case, since these native parts are part of the JOCL jars distributed via Maven.

So let's try some more digging from the repl:

```
lein repl
(select-keys (System/getProperties) ["java.version" "java.library.path" "os.arch"])
```

Btw. If you had the Oracle JDK you should be able to launch the Java Webstart demo on the JOCL site. It seems you have yet another JDK...

**Comment by cdlm** [comment]
```
user=> (select-keys (System/getProperties) ["java.version" "java.library.path" "os.arch"])
{"java.version" "1.8.0_45", "java.library.path" "/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native:/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native", "os.arch" "x86_64"}
```

Yes, I have the 1.6, 1.7, and 1.8 versions, plus `jenv` to switch between them. Thing is, depending on the packages, the JRE/JDK seem to install in a couple of different places in OS X (`/Library/Java/JavaVirtualMachines` and under `/Library/Internet Plugins/`. No idea what's the logic for picking one or the other… Maybe something is broken on my system but it's the same, zero clue about what/where/how…

**Comment by cdlm** [comment]
user=> (select-keys (System/getProperties) ["java.version" "java.library.path" "os.arch"])
{"java.version" "1.8.0_45", "java.library.path" "/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native:/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native", "os.arch" "x86_64"}

Yes, I have the 1.6, 1.7, and 1.8 versions, plus `jenv` to switch between them. Thing is, depending on the packages, the JRE/JDK seem to install in a couple of different places in OS X (`/Library/Java/JavaVirtualMachines` and under `/Library/Internet Plugins/`. No idea what's the logic for picking one or the other…

**Comment by cdlm** [comment]
user=> (select-keys (System/getProperties) ["java.version" "java.library.path" "os.arch"])
{"java.version" "1.8.0_45", "java.library.path" "/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native:/Users/damien/Documents/Scratch/clojure/raymarchcl/target/native", "os.arch" "x86_64"}

Yes, I have the 1.6, 1.7, and 1.8 versions, plus `jenv` to switch between them. Thing is, depending on the packages, the JRE/JDK seem to install in a couple of different places in OS X (`/Library/Java/JavaVirtualMachines` and under `/Library/Internet Plugins/`). No idea what's the logic for picking one or the other…

**Comment by postspectacular** [comment]
Weird, weird... Running out of options and ideas :( Do you see the 2 files below in your `target/native` folder of the project?

libgluegen-rt.jnilib
libjocl.jnilib

**Comment by cdlm** [comment]
Yes, they're here and `file` reports them as Mach-O binaries with support for both i386 and x86_64.
